baseURL = "https://asifimranaziz.github.io/personal-site-2026"
languageCode = "en-us"
title = "Asif Aziz - Personal Projects and CV"

[params]
  description = "Personal site for projects and CV"

[markup.goldmark.renderer]
  unsafe = true